// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN3eEbeujAKw1_JK6OcG4sY1uMs1BDF60',
    appId: '1:1033680828169:web:aebcd3146862d6191885d8',
    messagingSenderId: '1033680828169',
    projectId: 'mynotes-vandad-course',
    authDomain: 'mynotes-vandad-course.firebaseapp.com',
    storageBucket: 'mynotes-vandad-course.appspot.com',
    measurementId: 'G-P1RDEH6WBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyTJddqJ7aSl33LWSDw52nmf2EXeOXDDk',
    appId: '1:1033680828169:android:1d80400db90484dd1885d8',
    messagingSenderId: '1033680828169',
    projectId: 'mynotes-vandad-course',
    storageBucket: 'mynotes-vandad-course.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnVeUuP1bgGlfcRDRHy2Nd7DANq89_6fM',
    appId: '1:1033680828169:ios:a5bc81073ed96cd11885d8',
    messagingSenderId: '1033680828169',
    projectId: 'mynotes-vandad-course',
    storageBucket: 'mynotes-vandad-course.appspot.com',
    iosClientId: '1033680828169-gikouauipc4pp6edtt9u2g11m19qi5sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.freeFlutterCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnVeUuP1bgGlfcRDRHy2Nd7DANq89_6fM',
    appId: '1:1033680828169:ios:a5bc81073ed96cd11885d8',
    messagingSenderId: '1033680828169',
    projectId: 'mynotes-vandad-course',
    storageBucket: 'mynotes-vandad-course.appspot.com',
    iosClientId: '1033680828169-gikouauipc4pp6edtt9u2g11m19qi5sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.freeFlutterCourse',
  );
}
